# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
# https://github.com/hashicorp/setup-terraform

# Fragen:
# Warum nicht bei Merge 
name: Push to main branch

on:
  pull_request:
    branches:
      - main

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Echo Hello World
      run: echo "Hello, World!"

  terraform-fmt-init-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ">= 1.8.3"

    - name: Terraform fmt
      run: terraform fmt -check -recursive
      continue-on-error: false
    
    - name: Terraform Init and Validate
      run: |
        dirs=$(git diff --name-status origin/main | grep "^M\|^A" | grep ".tf" | awk '{print $2}' | xargs -I {} dirname {} | sort -u)
        echo "::set-output name=dirs::${dirs}"
        for dir in ${dirs}; do
          cd $dir
          terraform init -backend=false
          terraform validate -no-color
        done




