name: Push to main branch

on:
  push:
    branches:
      - '*'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Hello World
      run: echo "Hello, World!"


