#https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
name: Push to main branch

on:
  push:
    branches:
      - '*'

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Echo Hello World
      run: echo "Hello, World!"

  terraform-fmt-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ">= 1.8.3"

    - name: Terraform fmt
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color



